setwd("~/Documents/cloga.github.io/notebook")
WHO = read.csv('WHO.csv')
str(WHO)
#install.packages('ggplot2')
library(ggplot2)
scatterplot = ggplot(WHO, aes(x = GNI, y = FertilityRate))
colors()
scatterplot + geom_point()
scatterplot + geom_line()
dev.off()
ggplot(WHO, aes(x = log(FertilityRate), y = Under15)) + geom_point() + stat_smooth(method='lm')
ggplot(WHO, aes(x = FertilityRate, y = Under15)) + geom_point() + scale_color_brewer(palette="Dark2")
ggplot(WHO, aes(x = FertilityRate, y = Under15, color = Region)) + geom_point() + scale_color_brewer(palette="Dark2")

#VIDEO 3: A LINE PLOT
mvt = read.csv('mvt.csv', stringsAsFactors=FALSE)
str(mvt)
mvt$Date = strptime(mvt$Date, format='%m/%d/%y %H:%M')
mvt$Weekday = weekdays(mvt$Date)
mvt$Hour = mvt$Date$hour
str(mvt)
table(mvt$Weekday)
WeekdayCounts = as.data.frame(table(mvt$Weekday))
str(WeekdayCounts)
library(ggplot2)
ggplot(WeekdayCounts, aes(x = Var1, y =  Freq)) + geom_line(aes(group=1)) + xlab('Day of the Week') + ylab('Total Motor Thefts')
WeekdayCounts$Var1 = factor(WeekdayCounts$Var1, ordered =TRUE, levels= c('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'))
table(WeekdayCounts$Var1)
ggplot(WeekdayCounts, aes(x = Var1, y =  Freq)) + geom_line(aes(group=1), linetype=2) + xlab('Day of the Week') + ylab('Total Motor Thefts')
ggplot(WeekdayCounts, aes(x = Var1, y =  Freq)) + geom_line(aes(group=1), alpha=0.3) + xlab('Day of the Week') + ylab('Total Motor Thefts')
table(mvt$Weekday, mvt$Hour)
DayHourCounts = as.data.frame(table(mvt$Weekday, mvt$Hour))
str(DayHourCounts)
DayHourCounts$Hour = as.numeric(as.character(DayHourCounts$Var2))
ggplot(DayHourCounts, aes(x = Hour, y = Freq)) + geom_line(aes(group=Var1))
ggplot(DayHourCounts, aes(x = Hour, y = Freq)) + geom_line(aes(group=Var1, color=Var1), size=2)
DayHourCounts$Var1 = factor(DayHourCounts$Var1, ordered=TRUE,levels= c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'))
ggplot(DayHourCounts, aes(x = Hour, y = Var1)) +geom_tile(aes(fill=Freq))
ggplot(DayHourCounts, aes(x = Hour, y = Var1)) +geom_tile(aes(fill=Freq)) + scale_fill_gradient(name='Total MV Thefts', low='white', high='red') + theme(axis.title.y=element_blank())
ggplot(DayHourCounts, aes(x = Hour, y = Var1)) +geom_tile(aes(fill=Freq)) + scale_fill_gradient(name='Total MV Thefts', low='white', high='red') + theme(axis.title.y=element_blank())
ggplot(DayHourCounts, aes(x = Hour, y = Var1)) +geom_tile(aes(fill=Freq)) + scale_fill_gradient(name='Total MV Thefts', low='white', high='black') + theme(axis.title.y=element_blank())
install.packages('maps')
install.packages('ggmap')
library(maps)
library(ggmap)
chicago = get_map(location='chicago', zoom=11)
beijing = get_map(location='beijing', zoom=11)
ggmap(beijing)
ggmap(chicago) + geom_point(data=mvt[1:100,], aes(x = Longitude, y = Latitude))
LatLonCounts = as.data.frame(table(round(mvt$Longitude, 2), round(mvt$Latitude, 2)))
str(LatLonCounts)
LatLonCounts$Long = as.numeric(as.character(LatLonCounts$Var1))
LatLonCounts$Lat = as.numeric(as.character(LatLonCounts$Var2))
str(LatLonCounts)
ggmap(chicago) + geom_point(data=LatLonCounts, aes(x = Long, y = Lat, color = Freq, size = Freq)) + scale_color_gradient(low='yellow', high='red')
ggmap(chicago) + geom_tile(data=LatLonCounts, aes(x = Long, y = Lat, alpha = Freq, fill = 'red'))
LatLonCounts2 = LatLonCounts[LatLonCounts$Freq > 0,]
ggmap(chicago) + geom_tile(data=LatLonCounts2, aes(x = Long, y = Lat, alpha = Freq, fill = 'red'))
str(LatLonCounts2)
str(LatLonCounts)
#VIDEO 6: A HEATMAP ON THE UNITED STATES
murders = read.csv('murders.csv')
str(murders)
statsMap=map_data('state')
str(statsMap)
ggplot(statsMap, aes(x = long, y = lat ,group = group)) + geom_polygon(fill = 'white', color = 'black') + coord_map('mercator')
murders$region=tolower(murders$State)
murderMap = merge(statsMap, murders, by='region')
str(murderMap)
ggplot(murderMap, aes(x = long, y = lat, group = group, fill = Murders)) + geom_polygon(color='black') + scale_fill_gradient(low='black', high = 'red', guide='legend')
ggplot(murderMap, aes(x = long, y = lat, group = group, fill = Population)) + geom_polygon(color='black') + scale_fill_gradient(low='black', high = 'red', guide='legend')
murderMap$MurderRate = murderMap$Murders / murderMap$Population * 100000
ggplot(murderMap, aes(x = long, y = lat, group = group, fill = MurderRate)) + geom_polygon(color='black') + scale_fill_gradient(low='black', high = 'red', guide='legend')
ggplot(murderMap, aes(x = long, y = lat, group = group, fill = MurderRate)) + geom_polygon(color='black') + scale_fill_gradient(low='black', high = 'red', guide='legend', limits = c(0.9, 10))
ggplot(murderMap, aes(x = long, y = lat, group = group, fill = GunOwnership)) + geom_polygon(color='black') + scale_fill_gradient(low='black', high = 'red', guide='legend')
#VIDEO 3: BAR CHARTS IN R
intl = read.csv('intl.csv')
str(intl)
ggplot(intl, aes(x = Region, y = PercentOfIntl)) + geom_bar(stat = 'identity') + geom_text(aes(label=PercentOfIntl))
intl = transform(intl, Region = reorder(Region, -PercentOfIntl))
str(intl)
intl$PercentOfIntl = intl$PercentOfIntl*100
ggplot(intl, aes(x = Region, y = PercentOfIntl)) + geom_bar(stat = 'identity', fill='dark blue') + geom_text(aes(label=PercentOfIntl), vjust=-0.4) + ylab('Percent Of International Students') + theme(axis.title.x=element_blank(), axis.text.x = element_text(angle =45, hjust = 1))
intlall = read.csv('intlall.csv', stringsAsFactor=FALSE)
head(intlall)
intlall[is.na(intlall)] = 0
world_map = map_data('world')
str(world_map)
world_map = merge(world_map, intlall, by.x='region', by.y= 'Citizenship')
ggplot(world_map, aes(x=long, y = lat , group = group)) + geom_polygon(fill='white', color = 'black') + coord_map('mercator')
world_map = world_map[order(world_map$group, world_map$order),]
library(reshape2)
#ELECTION FORECASTING REVISITED
statesMap = map_data("state")
table(statesMap$group)
ggplot(statesMap, aes(x = long, y = lat, group = group)) + geom_polygon(fill = "white", color = "black") + coord_map("mercator")
polling = read.csv('PollingImputed.csv')
str(polling)
table(polling$Year)
Train = polling[(polling$Year == 2004 | polling$Year == 2004),]
Test = polling[(polling$Year == 2012),]
mod2 = glm(Republican~SurveyUSA+DiffCount, data=Train, family="binomial")
TestPrediction = predict(mod2, newdata=Test, type="response")
TestPredictionBinary = as.numeric(TestPrediction > 0.5)
predictionDataFrame = data.frame(TestPrediction, TestPredictionBinary, Test$State)
str(predictionDataFrame)
table(predictionDataFrame)
table(TestPrediction > 0.5)
mean(TestPrediction)
predictionDataFrame$region = tolower(predictionDataFrame$Test.State)
predictionMap = merge(statesMap, predictionDataFrame, by = "region")
predictionMap = predictionMap[order(predictionMap$order),]
str(predictionMap)
str(statesMap)
ggplot(predictionMap, aes(x = long, y = lat, group = group, fill = TestPredictionBinary)) + geom_polygon(color = "black")
ggplot(predictionMap, aes(x = long, y = lat, group = group, fill = TestPredictionBinary)) + geom_polygon(color = "black")
ggplot(predictionMap, aes(x = long, y = lat, group = group, fill = TestPredictionBinary))+ geom_polygon(color = "black") + scale_fill_gradient(low = "blue", high = "red", guide = "legend", breaks= c(0,1), labels = c("Democrat", "Republican"), name = "Prediction 2012")
ggplot(predictionMap, aes(x = long, y = lat, group = group, fill = TestPrediction))+ geom_polygon(color = "black", linetype=2, size=10, alpha=0.3) + scale_fill_gradient(low = "blue", high = "red", guide = "legend", breaks= c(0,1), labels = c("Democrat", "Republican"), name = "Prediction 2012")
predictionMap
str(predictionDataFrame)
predictionDataFrame[predictionDataFrame$region =='florida',]
predictionDataFrame
?geom_polygon
#VISUALIZING ATTRIBUTES OF PAROLE VIOLATORS
parole = read.csv('parole.csv')
str(parole)
parole$male = as.factor(parole$male)
parole$state = as.factor(parole$state)
parole$crime = as.factor(parole$crime)
table(parole$violator, parole$male)
14/(64+14)
table(parole$state)
table(parole[parole$state == 2,c('crime')])
ggplot(data = parole, aes(x = age)) + geom_histogram(binwidth = 5, color="blue")
ggplot(data = parole, aes(x = age)) + geom_histogram(binwidth = 5) + facet_grid(male ~ .)
ggplot(data = parole, aes(x = age)) + geom_histogram(binwidth = 5) + facet_grid(. ~ male)
ggplot(data = parole, aes(x = age, fill = male)) + geom_histogram(binwidth = 5, position="identity", alpha=0.5)
ggplot(data = parole, aes(x = time.served)) + geom_histogram(binwidth = 0.1, color="blue")
ggplot(data = parole, aes(x = time.served)) + geom_histogram(binwidth = 1, color="blue") + facet_grid(crime ~ .)
ggplot(data = parole, aes(x = age, fill = crime)) + geom_histogram(binwidth = 5, position="identity", alpha=0.5)
install.packages('igraph')
edges = read.csv('edges.csv')
users = read.csv('users.csv')
str(users)
str(edges)
mean(table(edges$V1))
mean(table(edges$V2))
sum(table(edges$V1))
length(table(edges$V1))
sum(table(edges$V2))
length(table(edges$V2))
str(as.data.frame(table(edges$V2)))
as.data.frame(table(edges$V1))
merge(as.data.frame(table(edges$V2)), as.data.frame(table(edges$V1)), by.x='Var2', by.y='Var1')
str(edges)
mean(table(c(edges$V1, edges$V2)))
sum(table(c(edges$V1, edges$V2)))
length(table(c(edges$V1, edges$V2)))
table(users$locale)
292/52
table(users$locale, users$gender)
users$gender
users$locale
library(igraph)
?graph.data.frame
g = graph.data.frame(edges, FALSE, users) 
plot(g, vertex.size=5, vertex.label=NA)
table(degree(g) >= 10)
V(g)$size = degree(g)/2+2
plot(g, vertex.label=NA)
max(V(g)$size)
min(V(g)$size)
V(g)$color = "black"
V(g)$color[V(g)$gender == "A"] = "red"
V(g)$color[V(g)$gender == "B"] = "gray"
V(g)$color[V(g)$locale == "A"] = "red"
V(g)$color[V(g)$locale == "B"] = "gray"
plot(g, vertex.label=NA)
?igraph.plotting
tweets = read.csv('tweets.csv', stringsAsFactors=FALSE)
